- name: Add BeyondCompare key
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt_key:
    url: http://www.scootersoftware.com/RPM-GPG-KEY-scootersoftware
    state: present

- name: Add BeyondCompare repo
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt_repository:
    repo: deb http://www.scootersoftware.com/ bcompare4 non-free
    state: present
    update_cache: yes

- name: Add deadsnakes ppa
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install standard niceties
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  pacman:
    name: "{{ packages }}"
  vars:
    packages:
      - ansible-lint
      - autoconf
      - automake
      - cloc
      - cmake
      - dconf-editor
      - dnsutils
      - flameshot
      - gnome-calculator
      - gpaste
      - imagemagick
      - inotify-tools
      - iperf3
      - jq
      - live-media
      - meld
      - minicom
      - ncdu
      - net-tools
      - nmap
      - nodejs
      - noto-fonts
      - noto-fonts-emoji
      - npm
      - ntp
      - numlockx
      - otf-fantasque-sans-mono
      - papirus-icon-theme
      - rofi
      - rofimoji
      - rsync
      - samba
      - sshfs
      - the_silver_searcher
      - ttf-inconsolata
      - ttf-liberation
      - vlc
      - wireguard-tools
      - wireshark-qt
      - xdotool
      - yarn
      - yamllint

- name: Install yay-bin
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: yay-bin

- name: Install AUR niceties
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ packages }}"
  vars:
    packages:
      - bcompare
      # - pamac-aur

- name: Install niceties
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - autoconf
      - automake
      - bcompare
      - cloc
      - cmake
      - dconf-cli
      - dconf-editor
      - fonts-fantasque-sans
      - fonts-fantasque-nerd
      - fonts-inconsolata
      - fonts-noto
      - inotify-tools
      - iperf3
      - jq
      - meld
      - minicom
      - ncdu
      - nmap
      - samba
      - sshfs
      - silversearcher-ag
      - uuid-runtime
      - vlc
      - wireguard-tools
      - wireshark
      - xdotool

- name: Add user to the wireshark group
  become: yes
  user:
    name: "{{ user }}"
    groups: [wireshark]
    append: yes

- name: Clone gogh for terminal color schemes
  tags: [justme]
  git:
    repo: https://github.com/Gogh-Co/Gogh.git
    dest: "{{ home }}/opt/gogh"

- name: start and enable NTP
  become: yes
  systemd:
    name: ntpd
    state: started
    enabled: yes

- name: Enable gnome-keyring SSH-Agent
  systemd:
    name: gcr-ssh-agent.socket
    state: started
    enabled: yes
    scope: user
  tags: [justme]
