- name: Add BeyondCompare key
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt_key:
    url: http://www.scootersoftware.com/RPM-GPG-KEY-scootersoftware
    state: present

- name: Add BeyondCompare repo
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt_repository:
    repo: deb http://www.scootersoftware.com/ bcompare4 non-free
    state: present
    update_cache: yes

- name: Add deadsnakes ppa
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Install standard niceties
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  pacman:
    name: "{{ packages }}"
  vars:
    packages:
      - autoconf
      - automake
      - cloc
      - cmake
      - dconf-editor
      - inotify-tools
      - iperf3
      - jq
      - meld
      - minicom
      - ncdu
      - nmap
      - noto-fonts
      - noto-fonts-emoji
      - numlockx
      - otf-fantasque-sans-mono
      - papirus-icon-theme
      - samba
      - sshfs
      - the_silver_searcher
      - ttf-inconsolata
      - vlc
      - wireguard-tools
      - wireshark-qt
      - xdotool

- name: Install AUR niceties
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: "{{ packages }}"
  vars:
    packages:
      - bcompare
      - pamac-aur

- name: Install niceties
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - autoconf
      - automake
      - bcompare
      - cloc
      - cmake
      - dconf-editor
      - fonts-fantasque-sans
      - fonts-inconsolata
      - fonts-noto
      - inotify-tools
      - iperf3
      - jq
      - meld
      - minicom
      - ncdu
      - nmap
      - samba
      - sshfs
      - silversearcher-ag
      - vlc
      - wireguard-tools
      - wireshark
      - xdotool

- name: Clone base16-gnome-terminal for terminal color schemes
  git:
    repo: https://github.com/aaron-williamson/base16-gnome-terminal.git
    dest: "{{ home }}/.config/base16-gnome-terminal"
