- name: Install packages
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - 1password
    - 1password-cli
    - aws-cli-v2
    - tailscale

- name: Install hooch development packages
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  community.general.pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - clang
    - cppcheck
    - doxygen
    - gcovr
    - jq
    - ninja
    - qemu-user
    - pkgconf

- name: Build and Install Fwup
  block:
  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/fwup-home/fwup.git'
      dest: "{{ home }}/opt/fwup"
      version: v1.10.1
      update: false

  - name: Build
    ansible.builtin.shell:
      chdir: "{{ home }}/opt/fwup"
      cmd: ./autogen.sh && ./configure && make
      creates: "{{ home }}/opt/fwup/src/fwup"

  - name: Install
    file:
      src: "{{ home }}/opt/fwup/src/fwup"
      dest: "{{ home }}/bin/fwup"
      state: link
      force: yes
