- name: Install packages
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - aws-cli
    - zerotier-one

- name: Install hooch development packages
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - clang
    - cppcheck
    - doxygen
    - gcovr
    - jq
    - ninja
    - qemu-user
    - pkgconf

- name: Enable zerotier-one
  become: yes
  systemd:
    name: zerotier-one
    state: started
    enabled: yes

- name: update /etc/hosts
  become: yes
  lineinfile:
    path: /etc/hosts
    line: "{{ item.ip }}  {{ item.hostname }}"
    regex: "{{ item.hostname }}"
  with_items:
    - hostname: nathan-desktop-zt
      ip: "{{ zerotier_address_desktop }}"
    - hostname: nathan-laptop-zt
      ip: "{{ zerotier_address_laptop }}"
    - hostname: nathan-macbook-zt
      ip: "{{ zerotier_address_macbook }}"
