- hosts: all
  vars:
    home: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"
    dotfiles_local: "{{ playbook_dir}}/.."
    local_run: "{{ ansible_host in ['localhost', '127.0.0.1', '::1'] or ansible_connection == 'local' }}"
    vim_bundle_dir:  "{{ home }}/.config/nvim/bundle"
  pre_tasks:
    - name: Set extra facts
      tags: [always]
      block:
      - name: Check for private key
        stat:
          path: .ssh/id_rsa
        register: privkey_stat
      - name: Set variable if private key exists
        set_fact:
            has_private_key: "{{privkey_stat.stat.exists}}"
      - name: Populate service facts
        ansible.builtin.service_facts:

  roles:
    - common
    - personal
    - niceties
    - home_network
    - bluetooth
    - docker
    # - i3
    - systemd-networkd
    - role: systemd-resolved
      when: ansible_facts.services.get('systemd-resolved.service')
    - elixir
    - flutter
    - tangotango
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: [never, debug]
