- hosts: all
  vars:
    home: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"
    dotfiles_local: "{{ playbook_dir}}/.."
  pre_tasks:
    - name: Set dynamic facts
      tags: [always]
      block:
      - name: Check for private key
        stat:
          path: .ssh/id_rsa
        register: privkey_stat
      - name: Set variable if private key exists
        set_fact:
            has_private_key: "{{privkey_stat.stat.exists}}"
  roles:
    - common
    - adtran
    - personal
    - niceties
    - home_network
    - i3
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
      tags: [debug]
