- hosts: all
  vars:
    home: "{{ ansible_env.HOME }}"
    user: "{{ ansible_env.USER }}"
    dotfiles_local: "{{ playbook_dir}}/.."
    # does this host have my private key installed? (must be transferred separately)
    has_private_key: true
  roles:
    - common
    - adtran
    - i3
