- name: Install packages
  when: ansible_facts['os_family'] == "Archlinux"
  become: yes
  pacman:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - blueman
      - bluez
      - bluez-utils
      - pulseaudio-bluetooth

- name: Start and enable bluetooth
  become: yes
  systemd:
    name: bluetooth
    state: started
    enabled: yes
