- name: Install niceties
  when: ansible_facts['os_family'] == "Debian"
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - autorandr
      - i3
      - rofi
      - xautolock
      - xss-lock

- name: Install config files
  file:
    src: "dotfiles/{{ item }}"
    dest: "{{ home }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - .i3
    - .i3status.conf
