ro = [
    "~/tmp",
    "~/.local/share/claude",
    "~/.config",
    "~/.gitconfig",
    "/proc",
    "/dev/urandom",
    "/etc/rsolv.conf",
    "/etc/nsswitch.conf",
    "/run/systemd/resolve/stub-resolv.conf",
    "/etc/hosts",
    "/etc/hostname",
    "/etc/ssl/certs",
    "/etc/ssl/openssl.cnf",
    "/etc/ca-certificates",
]
rw = ["~/.claude", "~/.claude.json", "/tmp", "/dev/null"]
rox = ["/usr/bin", "/usr/lib", "/opt/claude-code/bin", "~/.asdf"]
rwx = [".", "./.*", "~/.augment"]

env = ["COLORTERM", "EDITOR", "HOME", "LANG", "PATH", "SHELL", "TERM", "USER"]
