- name: Install stoken
  become: yes
  when: ansible_facts['os_family'] == "Debian"
  apt:
    name:
      - stoken

- name: Clone adtran-utils
  when: not local_run
  git:
    repo: git@github.adtran.com:nalderso/adtran-utils.git
    dest: "{{ home }}/adtran-utils"
    accept_hostkey: yes
    update: yes

- name: Get all adtran-utils scripts
  find:
    paths: "{{ home }}/adtran-utils/bin"
  register: adtran_utils

- name: Install adtran-utils scripts
  file:
    src: "{{ item.path }}"
    dest: "{{ home }}/bin/{{ item.path | basename }}"
    state: link
    force: yes
  with_items: "{{ adtran_utils.files }}"

- name: Configure pip
  file:
    src: "{{ home }}/adtran-utils/pip.conf"
    dest: "{{ home }}/.config/pip/pip.conf"
    state: link
    force: yes

- name: Install porg
  # This one has problems using a local connection because you end up still
  # in the virtualenv being used to run the playbook.
  when: ansible_connection != 'local'
  pip:
    extra_args: "--user"
    state: latest
    name: porg

- name: Configure porg
  file:
    src: "{{ home }}/adtran-utils/porg.toml"
    dest: "{{ home }}/.config/porg.toml"
    state: link
    force: yes

